version: '3.9'
services:
  solana-container:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    command: >
      /bin/bash -c "
        pwd
        /bin/bash
      "   
    volumes:
      - .:/app